# Install these tools via Ansible
- name: Install basic tools
  hosts: localhost
  become: false # false = admin rights aren't required
  tasks:
    - name: Install exercism
      community.general.homebrew:
        name: exercism
    - name: Install signal
      community.general.homebrew_cask:
        name: signal
    - name: Install macfuse
      community.general.homebrew_cask:
        name: macfuse
    - name: Install protonmail-bridge
      community.general.homebrew_cask:
        name: protonmail-bridge
    - name: Install whatsapp
      community.general.homebrew_cask:
        name: whatsapp
