# Install these tools via Ansible
- name: Install basic tools
  hosts: localhost
  become: false # false = admin rights aren't required
  tasks:
    - name: Install k9s
      community.general.homebrew:
        name: k9s
    - name: Install git-flow-avh
      community.general.homebrew:
        name: git-flow-avh
